FROM openjdk:17.0.2-jdk
RUN microdnf install curl ca-certificates ${JAVA_PACKAGE} \
    && microdnf update \
    && microdnf clean all

LABEL maintainer="sig-platform@spinnaker.io"
RUN  microdnf install --setopt=tsflags=nodocs openssh-clients && \
  groupadd -g 10111 spinnaker && \
  useradd -g spinnaker -u 10111 spinnaker
COPY fiat-web/build/install/fiat /opt/fiat
RUN mkdir -p /opt/fiat/plugins && chown -R spinnaker /opt/fiat/plugins
USER spinnaker
CMD ["/opt/fiat/bin/fiat"]



